const portfolioImageNumbers = Array.from({ length: 40 }, (_, i) => i);

const portfolioImageAltTexts = [
  "AI-generated fragrance product shoot with premium studio lighting",
  "AI-generated D2C perfume ad creative with lifestyle composition",
  "Synthetic product photography for fragrance campaign assets",
  "AI-generated ecommerce product visual for perfume packaging",
  "Creative ad render for fragrance SKU campaign",
  "AI-assisted product shoot for D2C fragrance marketing",
  "Generated brand campaign image for perfume social ads",
  "AI-native product photography test for fragrance bottles",
  "Generated video testimonial thumbnail for fragrance growth work",
  "AI-generated campaign visual for SKU creative delivery",
  "Synthetic editorial product shoot for perfume campaign content",
  "AI-assisted fragrance ad asset with model and product styling",
  "Generated product-led social creative for consumer fragrance",
  "AI-native studio shoot for perfume bottle merchandising",
  "Generated Meta ad creative for D2C fragrance performance tests",
  "AI-generated product and lifestyle composition for perfume ads",
  "Synthetic fragrance campaign image for paid social storytelling",
  "AI-assisted consumer brand visual for ecommerce and paid social",
  "Generated product detail shoot for premium fragrance packaging",
  "AI-generated creative asset for perfume SKU campaign system",
  "Generated fragrance ad concept for product-consistent creatives",
  "AI-generated perfume lifestyle shoot for social campaign testing",
  "Synthetic product image for Amazon, Meta, and website assets",
  "Generated creator-style fragrance ad for campaign experiments",
  "AI-assisted product shoot for brand-trained creative pipeline",
  "Generated fragrance ecommerce image with consistent bottle styling",
  "AI-native paid social creative for D2C perfume growth",
  "Synthetic campaign visual for fragrance market testing",
  "Generated premium perfume product shoot for campaign assets",
  "AI-assisted ad creative for consumer fragrance brands",
  "Generated SKU visual for Renderless product creative pipeline",
];

export const siteConfig = {
  siteUrl: "https://renderless.agency",
  heroHeader: "RENDERLESS",
  subtext: "Meta and TikTok campaigns for D2C brands. No shoots. No renders. First campaign live in under 1 week.",
  proofLine: "Backed by world-class startup programs.",
  seo: {
    title: "Renderless | Performance Creative Agency for D2C Brands",
    shortTitle: "Renderless",
    description:
      "Renderless runs Meta and TikTok campaigns for D2C brands, generating ad assets without shoots or renders and building the market-listening loop around each campaign.",
    keywords: [
      "AI generated ads",
      "AI product photography",
      "AI product shoots",
      "performance creative agency",
      "Meta campaign management",
      "TikTok campaign management",
      "D2C growth agency",
      "fragrance marketing",
      "perfume product photography",
      "AI creative pipeline",
      "Meta ad creatives",
      "creator research",
      "social listening",
      "performance dashboards",
      "consumer brand growth",
    ],
    ogImages: [
      {
        url: "/portfolio/work-1.webp",
        width: 1200,
        height: 1600,
        alt: "AI-generated fragrance product shoot by Renderless",
      },
      {
        url: "/portfolio/work-5.webp",
        width: 1200,
        height: 1600,
        alt: "AI-generated D2C fragrance ad creative by Renderless",
      },
      {
        url: "/portfolio/work-10.webp",
        width: 1200,
        height: 1600,
        alt: "AI-assisted product creative for fragrance campaign assets",
      },
    ],
  },
  colors: { background: "#242424", text: "#FFFFFF", accent: "#CCFF00" },
  images: portfolioImageNumbers.map((number) => ({
    id: number,
    url: `/portfolio/work-${number}.webp`,
    alt: portfolioImageAltTexts[number] ?? `AI-generated Renderless portfolio image ${number}`
  })),
  navItems: ["MENU"],
  partnerPrograms: [
    { name: "NVIDIA Inception Program", logo: "/programs/nvidia-inception.png" },
    { name: "AWS Startups", logo: "/programs/aws-startups.png" },
    { name: "Microsoft for Startups", logo: "/programs/microsoft-for-startups.png" },
    { name: "Google for Startups", logo: "/programs/google-for-startups.png" },
  ],
  capabilities: [
    { 
      name: 'Campaign Buildout', 
      number: '01',
      description: 'We turn the brief into live Meta and TikTok tests: offer, angle, account setup, creative batches, reporting, and next moves.',
      image: '/portfolio/work-1.webp',
    },
    { 
      name: 'Social Scraping', 
      number: '02',
      description: 'We scrape comments, reviews, Reddit, TikTok, marketplace pages, and niche communities to find what customers already care about.',
      image: '/portfolio/work-2.webp',
    },
    { 
      name: 'Competitor Intelligence', 
      number: '03',
      description: 'We look at competitor campaigns, creator angles, listings, hooks, claims, and offer patterns before deciding what to test.',
      image: '/portfolio/work-3.webp',
    },
    { 
      name: 'SKU-Consistent Creative', 
      number: '04',
      description: 'We generate product visuals and ad variants around your brand identity, SKU details, packaging, price point, and campaign angle.',
      image: '/portfolio/work-4.webp',
    },
    {
      name: 'Misc Growth Hacks',
      number: '05',
      description: 'CRM automation, mailbox enrichment, product audits, scraper builds, listeners, dashboards, and odd jobs that unlock growth.',
      image: '/portfolio/work-6.webp',
    },
  ],
  caseStudies: [
    {
      brand: "Street Origins",
      label: "Meta retainer",
      subtext: "Paid social retainer, weekly creative refreshes, and sales reporting.",
      result: "",
      logo: "/brands/so.png",
      work: [
        "Meta ads",
        "Creative refresh",
        "Sales reporting",
        "Budget moves",
      ],
    },
    {
      brand: "French Avenue",
      label: "SKU pipeline",
      subtext: "Reusable SKU creative pipeline, marketplace checks, and creator direction.",
      result: "",
      logo: "/brands/fa.png",
      work: [
        "137 SKUs",
        "Listing checks",
        "Creator direction",
        "Asset pipeline",
      ],
    },
    {
      brand: "Fragrance World",
      label: "Growth ops",
      subtext: "CRM setup, social listening, distributor data, and product ops support.",
      result: "",
      logo: "/brands/fw.png",
      work: [
        "CRM setup",
        "Social listening",
        "Distributor data",
        "X management",
      ],
    },
  ],
  projectHighlights: [
    {
      label: "Campaign speed",
      title: "First campaign live in under 1 week",
      description: "Product, offer, creative, campaign structure, and first testing plan moved from brief to live batch without waiting on shoot production.",
    },
    {
      label: "Digital twins",
      title: "Creator clones for faster ad testing",
      description: "Digital twin workflows for influencer-style ads, with brand approval before scaling the best-performing direction.",
    },
    {
      label: "Audience mining",
      title: "Reddit psychographics and sentiment",
      description: "Thousands of niche posts and comments analyzed for ownership, story, objections, customer language, and campaign angles.",
    },
    {
      label: "Ops automation",
      title: "CRM, mailbox, and sheet workflows",
      description: "Semi-autonomous CRM, distributor enrichment, mailbox export mining, and Google Sheet automations that keep growth work moving.",
    },
  ],
  testimonials: [
    {
      name: "Nandit Dhandha",
      title: "Chief of Staff",
      company: "Street Origins",
      type: "Video testimonial",
      thumbnail: "/testimonials/nandit-dhandha.webp",
      linkedinUrl: "https://www.linkedin.com/in/nandit-dhanda/",
      note: "Campaign workflow, creative delivery, and retainer expansion.",
    },
    {
      name: "Gokulakannan P",
      title: "Business Head",
      company: "Fragrance World",
      type: "Video testimonial",
      thumbnail: "/testimonials/gokulakannan-p.webp",
      linkedinUrl: "https://www.linkedin.com/in/gokul1017/",
      note: "Growth ops, campaign systems, and product-data workflows.",
    },
  ],
  dataAdvantage: [
    "We keep track of winners, losers, comments, reviews, hooks, objections, creator angles, SKU learnings, and spend data.",
    "Each week, that turns into a new creative brief: what to scale, what to remake, what to kill, and what angle to test next.",
    "The result is not just more ads. It is a campaign system that gets closer to the customer every round.",
    "You get faster creative, more tests, fewer handoffs, and clearer decisions while the campaign is still live.",
  ],
};
